// Fontes exibidas nas telas "O que aconteceu" da v2
export const SRC2: Record<string, [string, string]> = {
  pec6x1: ['Congresso em Foco, 28/05/2026', 'https://www.congressoemfoco.com.br/noticia/119260/40-senadores-assinam-pec-alternativa-ao-fim-da-escala-6x1-veja-lista'],
  met6x1: ['Metrópoles, 06/10/2026', 'https://www.metropoles.com/brasil/flavio-critica-pec-da-6x1-e-volta-a-defender-regime-por-hora-liberdade'],
  datafolha: ['CNN Brasil (Datafolha), 15/03/2026', 'https://www.cnnbrasil.com.br/economia/macroeconomia/datafolha-71-dos-brasileiros-apoiam-fim-da-escala-6x1/'],
  dieese: ['DIEESE, Nota Técnica 289', 'https://www.dieese.org.br/notatecnica/2025/notaTec289salarioMinimo.pdf'],
  ustr: ['Federal Register (USTR), 04/06/2026', 'https://www.federalregister.gov/documents/2026/06/04/2026-11158/notice-of-determination-and-request-for-comments-concerning-action-pursuant-to-section-301-brazils'],
  istoepix: ['IstoÉ, 03/07/2026', 'https://istoe.com.br/flavio-bolsonaro-pix-eua-tarifas-documento-ustr'],
  reuterspix: ['Reuters, 21/07/2026', 'https://finance.yahoo.com/markets/currencies/articles/brazil-us-clash-over-future-100338890.html'],
  thanks: ['SBT News', 'https://sbtnews.sbt.com.br/noticia/politica/flavio-tambem-agradeceu-a-trump-por-tarifas-em-2025'],
  cesta: ['DGABC (Procon-SP/DIEESE), 18/08/2026', 'https://www.dgabc.com.br/Noticia/4341808/cesta-basica-fica-0-91-mais-barata-em-julho-na-capital-paulista-mostram-procon-sp-e-dieese'],
  farmacia: ['Estadão, 14/09/2022', 'https://mercadoeconsumo.com.br/14/09/2022/estadao-conteudo/corte-no-orcamento-da-farmacia-popular-atinge-13-medicamentos/'],
  folhapisos: ['Correio Braziliense, 22/04/2026', 'https://www.correiobraziliense.com.br/politica/2026/04/7403233-flavio-avalia-reajuste-de-gastos-sociais-pela-inflacao-e-mais-privatizacoes.html'],
  cnnpec: ['CNN Brasil, 25/09/2026', 'https://www.cnnbrasil.com.br/blogs/caio-junqueira/eleicoes/flavio-planeja-pec-da-transicao-com-corte-de-gastos-de-r-300-bilhoes/'],
  absorv: ['Agência Câmara, 2022', 'https://www.camara.leg.br/noticias/857388-congresso-derruba-veto-a-distribuicao-gratuita-de-absorventes/'],
  oeco: ['((o))eco, 22/12/2022', 'https://oeco.org.br/reportagens/relatorio-da-transicao-revela-que-com-bolsonaro-pais-enfrentou-aumento-de-60-no-desmatamento-e-perdeu-18-bi-em-multas/'],
  boiada: ['Poder360', 'https://www.poder360.com.br/governo/salles-sugere-ir-passando-a-boiada-para-mudar-regras-durante-pandemia/'],
  pl2159: ['Poder360, 05/2025', 'https://www.poder360.com.br/poder-congresso/licenca-ambiental-45-dos-votos-a-favor-foram-da-base-de-lula/'],
  amarras: ['Estado de Minas, 02/10/2026', 'https://www.em.com.br/politica/2026/10/7512979-para-ganhar-votos-flavio-promete-acabar-com-amarras-ambientais.html'],
  milicia2007: ['CartaCapital, 26/02/2020', 'https://www.cartacapital.com.br/?p=112973'],
  medalha: ['Jornal do Brasil, 01/2019', 'https://www.jb.com.br/rio/2019/01/975063-ex-pm-estava-preso-quando-foi-homenageado-por-flavio-bolsonaro.html'],
  marielle: ['Migalhas, 25/02/2026', 'https://www.migalhas.com.br/quentes/450632/stf-veja-penas-fixadas-pela-1-turma-a-mandantes-da-morte-de-marielle'],
  emenda: ['Estado de Minas, 23/09/2026', 'https://www.em.com.br/politica/2026/09/7506425-flavio-bolsonaro-destinou-emenda-a-miliciano-condenado-no-caso-marielle.html'],
  cac: ['IstoÉ Dinheiro, 31/08/2022', 'https://istoedinheiro.com.br/numero-de-armas-registradas-por-cacs-cresce-287-desde-2018-e-ultrapassa-1-milhao'],
  mjsp: ['MJSP, Mapa da Segurança Pública 2026', 'https://www.gov.br/mj/pt-br/assuntos/sua-seguranca/seguranca-publica/estatistica/download/mapa-de-seguranca-publica-2026.pdf/'],
  bijos: ['Agência Câmara, 05/11/2024', 'https://www.camara.leg.br/noticias/1108727-estudo-de-consultor-de-orcamento-da-camara-indica-medidas-para-ajuste-fiscal/'],
  reforma: ['Exame, 23/10/2019', 'https://exame.com/economia/confira-como-cada-senador-votou-na-reforma-da-previdencia'],
  careca: ['Estado de Minas, 12/09/2026', 'https://www.em.com.br/politica/2026/09/7499131-empresa-de-flavio-bolsonaro-divide-endereco-com-empresas-do-careca-do-inss.html'],
  cgu: ['InfoMoney, 02/05/2025', 'https://www.infomoney.com.br/politica/inss-41-milhoes-podem-ter-sido-vitimas-de-descontos-ilegais-aponta-cgu/'],
  anistia: ['InfoMoney, 28/08/2026', 'https://www.infomoney.com.br/politica/flavio-diz-que-buscara-anistia-para-bolsonaro-ainda-durante-governo-de-transicao/'],
  indulto: ['SBT News, 29/09/2026', 'https://sbtnews.sbt.com.br/noticia/politica/8-1-sem-anistia-darei-indulto-a-todo-mundo-diz-flavio'],
  stf: ['Times Brasil, 03/10/2026', 'https://timesbrasil.com.br/eleicoes-2026/flavio-defende-impeachment-de-ministros-do-stf/'],
  constituicao: ['Tribuna de Jundiaí, 06/10/2026', 'https://tribunadejundiai.com.br/politica/eleicoes-2026/flavio-bolsonaro-mudar-constituicao/'],
  mentiras: ['Aos Fatos', 'https://www.aosfatos.org/noticias/flavio-mentiu-ao-menos-43-vezes-sobre-envolvimento-com-vorcaro/'],
  faltas: ['NC News, 19/09/2026', 'https://ncnews.com.br/2026/09/19/flavio-destaca-comissao-de-seguranca-na-campanha-mas-faltou-a-72-das-sessoes/'],
  leis: ['Jornal de Brasília, 05/2026', 'https://jornaldebrasilia.com.br/noticias/politica-e-poder/flavio-bolsonaro-mirou-seguranca-mas-nao-teve-projetos-proprios-transformados-em-lei/']
};
